# Formulation of Jacobian for RSSR-SSR spatial parallel manipulator as an example

## Figure

![RSSR-SSR spatial parallel manipulator](../../images/RSSRSSR.png "RSSR-SSR spatial parallel manipulator")

## Jacobian

The topological information of a robot is to be specified by using its robot-topology matrix, as defined [here](../../../../misc/Robot_Topology_Matrix.md). For RSSR-SSR spatial parallel manipulator shown above, the robot topology matrix is given by

$$\left[\begin{matrix}9 & 1 & 1 & 0 & 1 & 0\\\\1 & 9 & 0 & 0 & 0 & 4\\\\1 & 0 & 9 & 4 & 0 & 0\\\\0 & 0 & 0 & 9 & 0 & 4\\\\0 & 0 & 0 & 0 & 9 & 4\\\\0 & 0 & 0 & 0 & 0 & 9\end{matrix}\right]$$

### Importing required modules

The corresponding Jacobian function can be formulated as follows.

In [1]:
from acrod.jacobian import Jacobian
from numpy import array

### Specifying Robot-Topology matrix and initialising jacobian class

The robot-topology matrix for RSSR-SSR spatial parallel manipulator is defined and jacobian information is processed via the imported jacobian class as follows.

In [2]:
M = array(
        [[9, 1, 1, 0, 1, 0],
         [1, 9, 0, 0, 0, 4],
         [1, 0, 9, 4, 0, 0],
         [0, 0, 0, 9, 0, 4],
         [0, 0, 0, 0, 9, 4],
         [0, 0, 0, 0, 0, 9]]
    )
jac = Jacobian(M)

### Generation of Jacobian function

Jacobian function is generated as shown below.

In [3]:
jacobian_function = jac.get_jacobian_function()

### Various attributes of the jacobian object

In the process of generating the above jacobian function, other attributes of the jacobian object also are updated. Symbolic Jacobian matrices can be extracted from the attributes. Since this is a non-serial robot, there would be four matrices required to compute the Jacobian, which are $J_a$, $J_p$, $A_a$ and $A_p$. These can be extracted by the attributes `Ja`, `Jp`, `Aa` and `Ap`, respectively, as shown below.

In [4]:
symbolic_Ja = jac.Ja
symbolic_Ja

Matrix([
[                  -(a_y - r_{(1,2)y})*cos(\beta_{(1,2)}) + (a_z - r_{(1,2)z})*sin(\beta_{(1,2)})*sin(\phi_{(1,2)}), 0],
[                   (a_x - r_{(1,2)x})*cos(\beta_{(1,2)}) - (a_z - r_{(1,2)z})*sin(\beta_{(1,2)})*cos(\phi_{(1,2)}), 0],
[-(a_x - r_{(1,2)x})*sin(\beta_{(1,2)})*sin(\phi_{(1,2)}) + (a_y - r_{(1,2)y})*sin(\beta_{(1,2)})*cos(\phi_{(1,2)}), 0],
[                                                                              sin(\beta_{(1,2)})*cos(\phi_{(1,2)}), 0],
[                                                                              sin(\beta_{(1,2)})*sin(\phi_{(1,2)}), 0],
[                                                                                                cos(\beta_{(1,2)}), 0]])

In [5]:
symbolic_Jp = jac.Jp
symbolic_Jp

Matrix([
[0,                 0,  a_z - r_{(2,6)z}, -a_y + r_{(2,6)y}, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, -a_z + r_{(2,6)z},                 0,  a_x - r_{(2,6)x}, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0,  a_y - r_{(2,6)y}, -a_x + r_{(2,6)x},                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0,                 1,                 0,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0,                 0,                 1,                 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0,                 0,                 0,                 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
symbolic_Aa = jac.Aa
symbolic_Aa

Matrix([
[                  (a_y - r_{(1,2)y})*cos(\beta_{(1,2)}) - (a_z - r_{(1,2)z})*sin(\beta_{(1,2)})*sin(\phi_{(1,2)}),                                                                                                                                                                              0],
[                 -(a_x - r_{(1,2)x})*cos(\beta_{(1,2)}) + (a_z - r_{(1,2)z})*sin(\beta_{(1,2)})*cos(\phi_{(1,2)}),                                                                                                                                                                              0],
[(a_x - r_{(1,2)x})*sin(\beta_{(1,2)})*sin(\phi_{(1,2)}) - (a_y - r_{(1,2)y})*sin(\beta_{(1,2)})*cos(\phi_{(1,2)}),                                                                                                                                                                              0],
[                  (a_y - r_{(1,2)y})*cos(\beta_{(1,2)}) - (a_z - r_{(1,2)z})*sin(\beta_{(1,2)})*sin(\phi_{(1,2)

In [7]:
symbolic_Ap = jac.Ap
symbolic_Ap

Matrix([
[                  -(a_y - r_{(1,5)y})*cos(\beta_{(1,5)}) + (a_z - r_{(1,5)z})*sin(\beta_{(1,5)})*sin(\phi_{(1,5)}),                 0, -a_z + r_{(2,6)z},  a_y - r_{(2,6)y},                       0,                       0,                       0,                 0,                 0,                 0,                 0,  a_z - r_{(5,6)z}, -a_y + r_{(5,6)y}],
[                   (a_x - r_{(1,5)x})*cos(\beta_{(1,5)}) - (a_z - r_{(1,5)z})*sin(\beta_{(1,5)})*cos(\phi_{(1,5)}),  a_z - r_{(2,6)z},                 0, -a_x + r_{(2,6)x},                       0,                       0,                       0,                 0,                 0,                 0, -a_z + r_{(5,6)z},                 0,  a_x - r_{(5,6)x}],
[-(a_x - r_{(1,5)x})*sin(\beta_{(1,5)})*sin(\phi_{(1,5)}) + (a_y - r_{(1,5)y})*sin(\beta_{(1,5)})*cos(\phi_{(1,5)}), -a_y + r_{(2,6)y},  a_x - r_{(2,6)x},                 0,                       0,                       0,                       0,               

The above matrices are based on the notations defined and described [here](../../../../misc/Notation_and_Nomenclature.md).

### Active joint velocities

Active joint velocities, in the corresponding order, can be viewed by running the following lines.

In [8]:
active_joint_velocities = jac.active_joint_velocities_symbolic
active_joint_velocities

Matrix([
[\dot{\theta}_{(1,2)}],
[\dot{\theta}_{(1,3)}]])

### Robot's dimensional parameters

The robot's dimensional parameters can be viewed by running the below line.

In [9]:
robot_dimensional_parameters = jac.parameters_symbolic
robot_dimensional_parameters

Matrix([
[   r_{(1,2)x}],
[   r_{(1,2)y}],
[   r_{(1,2)z}],
[\beta_{(1,2)}],
[ \phi_{(1,2)}],
[   r_{(1,3)x}],
[   r_{(1,3)y}],
[   r_{(1,3)z}],
[\beta_{(1,3)}],
[ \phi_{(1,3)}],
[   r_{(1,5)x}],
[   r_{(1,5)y}],
[   r_{(1,5)z}],
[\beta_{(1,5)}],
[ \phi_{(1,5)}],
[   r_{(2,6)x}],
[   r_{(2,6)y}],
[   r_{(2,6)z}],
[   r_{(3,4)x}],
[   r_{(3,4)y}],
[   r_{(3,4)z}],
[   r_{(4,6)x}],
[   r_{(4,6)y}],
[   r_{(4,6)z}],
[   r_{(5,6)x}],
[   r_{(5,6)y}],
[   r_{(5,6)z}]])

### Robot's end-effector parameters

The robot's end-effector parameters can be viewed by running the below line.

In [10]:
robot_endeffector_parameters = jac.endeffector_variables_symbolic
robot_endeffector_parameters

Matrix([
[a_x],
[a_y],
[a_z]])

### Sample computation of Jacobian for the configuration corresponding to the parameters shown below:

- End-effector point: $\textbf{a}=\hat{i}+2\hat{j}+3\hat{k}$
- Locations of joints: $\textbf{r}_{(1,2)}=2\hat{i}+8\hat{j}+3\hat{k}$, $\textbf{r}_{(1,3)}=1\hat{i}+2\hat{j}+5\hat{k}$, $\textbf{r}_{(1,5)}=2\hat{i}+4\hat{j}+7\hat{k}$, $\textbf{r}_{(2,6)}=3\hat{i}+1\hat{j}+2\hat{k}$, $\textbf{r}_{(3,4)}=6\hat{i}+8\hat{j}+4\hat{k}$, $\textbf{r}_{(4,6)}=8\hat{i}+1\hat{j}+3\hat{k}$ and $\textbf{r}_{(5,6)}=5\hat{i}+7\hat{j}+3\hat{k}$
- Orientations of joints: $\beta_{(1,2)}=\pi/6$, $\phi_{(1,2)}=\pi/3$, $\beta_{(1,3)}=5\pi/6$, $\phi_{(1,3)}=2\pi/3$, $\beta_{(1,5)}=\pi/12$ and $\phi_{(1,5)}=\pi/2$.

For the given set of dimensional parameters of the robot, the numerical Jacobian can be computed as follows. Firstly, we need to gather the configuration parameters in Python list format, in a particular order. The robot dimensional parameters from `jac.parameters_symbolic` are found (as shown earlier) to be in the order of $r_{(1,2)x}$, $r_{(1,2)y}$, $r_{(1,2)z}$, $\beta_{(1,2)}$, $\phi_{(1,2)}$, $r_{(1,3)x}$, $r_{(1,3)y}$, $r_{(1,3)z}$, $\beta_{(1,3)}$, $\phi_{(1,3)}$, $r_{(1,5)x}$, $r_{(1,5)y}$, $r_{(1,5)z}$, $\beta_{(1,5)}$, $\phi_{(1,5)}$, $r_{(2,6)x}$, $r_{(2,6)y}$, $r_{(2,6)z}$, $r_{(3,4)x}$, $r_{(3,4)y}$, $r_{(3,4)z}$, $r_{(4,6)x}$, $r_{(4,6)y}$, $r_{(4,6)z}$, $r_{(5,6)x}$, $r_{(5,6)y}$ and $r_{(5,6)z}$. Hence the configuration parameters are to be supplied in the same order, as a list. Thus, the computation can be performed as shown below.

In [11]:
from numpy import pi

end_effector_point = [1,2,3]
configuration_parameters = [2, 8, 3, pi/6, pi/3, 1, 2, 5, 5*pi/6, 2*pi/3, 2, 4, 7, pi/12, pi/2, 3, 1, 2, 6, 8, 4, 8, 1, 3, 5, 7, 3]
jacobian_at_the_given_configuration = jacobian_function(end_effector_point, configuration_parameters)
jacobian_at_the_given_configuration

array([[ 19.62196517,  10.77434097],
       [-16.1460825 ,  -8.61947278],
       [ 43.06469529,  30.16815472],
       [  6.57574977,   4.30973639],
       [ 19.33597911,  12.92920917],
       [  5.34317907,   2.15486819]])

### Accessing each matrix individually:

Each of $J_a$, $J_p$, $A_a$ and $A_p$ functions can be accessed as shown below

In [12]:
numerical_Ja = jac.Ja_func(end_effector_point, configuration_parameters)
numerical_Ja

array([[ 5.19615242,  0.        ],
       [-0.8660254 ,  0.        ],
       [-1.0669873 ,  0.        ],
       [ 0.25      ,  0.        ],
       [ 0.4330127 ,  0.        ],
       [ 0.8660254 ,  0.        ]])

In [13]:
numerical_Jp = jac.Jp_func(end_effector_point, configuration_parameters)
numerical_Jp

array([[ 0,  0,  1, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  0, -2,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [14]:
numerical_Aa = jac.Aa_func(end_effector_point, configuration_parameters)
numerical_Aa

array([[-5.19615242,  0.        ],
       [ 0.8660254 ,  0.        ],
       [ 1.0669873 ,  0.        ],
       [-5.19615242, -0.8660254 ],
       [ 0.8660254 , -0.5       ],
       [ 1.0669873 , -0.        ],
       [-0.25      ,  0.        ],
       [-0.4330127 ,  0.        ],
       [-0.8660254 ,  0.        ],
       [-0.25      , -0.25      ],
       [-0.4330127 ,  0.4330127 ],
       [-0.8660254 , -0.8660254 ],
       [ 0.        ,  2.66506351]])

In [15]:
numerical_Ap = jac.Ap_func(end_effector_point, configuration_parameters)
numerical_Ap.round()

array([[ 1.,  0., -1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  5.],
       [-1.,  1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -4.],
       [ 0., -1., -2.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -5.,  4.,  0.],
       [ 0.,  0., -1.,  1.,  0., -1.,  6.,  0.,  0., -1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  2.,  1.,  0., -5.,  0.,  0., -7.,  0.,  0.,  0.],
       [ 0., -1., -2.,  0., -6.,  5.,  0.,  1.,  7.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 0., -1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -2.,  7.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]])

And the computation $J_a-J_pA^{-1}_pA_a$ is given by the code below, which gives the same output as `jacobian_at_the_given_configuration`.

In [16]:
import numpy
numerical_Ja-numpy.matmul(numpy.matmul(numerical_Jp,numpy.linalg.inv(numerical_Ap)),numerical_Aa)

array([[ 19.62196517,  10.77434097],
       [-16.1460825 ,  -8.61947278],
       [ 43.06469529,  30.16815472],
       [  6.57574977,   4.30973639],
       [ 19.33597911,  12.92920917],
       [  5.34317907,   2.15486819]])

### Some other attributes

To get the computed list of all connecting paths from the base link to the end-effector link, the below script can be used, which gives the list of all connecting paths (only link numbers are shown, indexed from 0).

In [17]:
jac.P

[[0, 1, 5], [0, 4, 5], [0, 2, 3, 5]]

Out of the above paths, the computed list of independent paths pertaining to linear velocities and angular velocities, can be accessed by the below scripts:

For independent paths pertaining to linear velocities:

In [18]:
jac.P_tilde

[[0, 1, 5], [0, 4, 5], [0, 2, 3, 5]]

For independent paths pertaining to angular velocities:

In [19]:
jac.P_tilde_omega

[[0, 1, 5], [0, 4, 5], [0, 2, 3, 5]]

The above scripts give the lists of all the independent connecting paths pertaining to linear and angular velocities (only link numbers are shown, indexed from 0).

### Superfluous DOF information:

This manipulator has a superfluous DOF. The information of all the superfluous DOFs in the manipulator can be retrieved in a list by the script shown below:

In [20]:
superfluous_dof_information = jac.superfluous_dof_information
len(superfluous_dof_information)

1

The above output shows that the number of superfluous DOF is 1. In order to access the information of this superfluous DOF, the script shown below can be used:

In [21]:
c_be, [(i,j),(k,l)] = superfluous_dof_information[0]
[(i,j),(k,l)]

[(2, 3), (3, 5)]

The above output shows that the superfluous DOF exists between the spherical joints joined by links 3,4 and 4,6 (since the link numbers are indexed from zero). And `c_be` represents the list of link numbers of the part that contains base and end-effector links (as explained here). The complement list of `c_be` can be computed as shown below.

In [22]:
c_be_complement = [i for i in range(len(M)) if i not in c_be]
c_be_complement

[3]

This shows that it is the link 4 that exhibits a superfluous DOF, which is evident from the figure in the beginning of this document.

Note: In the above results, the link numbers are indexed from 0 (not 1).

# Mathematical derivation of Jacobian

The mathematical derivation is shown [here](../../maths/RSSR-SSR_serial-parallel_hybrid_robot.md).